name: TestPipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wwhds_one/test-Pipeline
          token: tnKD34RA3U4drEOWpWBOgqYwTXKf3z6vm6sonPuC
          # 如果 Gitea 实例使用 HTTP 协议，需要设置这个选项
          fetch-depth: 0
          # 以下两行设置 Gitea 仓库的 URL
          url: http://47.93.83.136:3000/Wwhds_one/test-Pipeline.git

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Update Go dependencies
        run: go get -u

      - name: Tidy Go modules
        run: go mod tidy

      - name: Build Docker image
        run: docker build -t go-testPipeline .
        # 构建 Docker 镜像，使用当前目录下的 Dockerfile

      - name: Start Docker container
        run: docker run -d --name go-testPipeline-container --network host go-testPipeline
        # 启动 Docker 容器